### ISSUE TITLE
Move repository to official minetest-mods

### ISSUE THREAD

**Issue by SmallJoker** [mt-mods/3d_armor#4]
I believe the official https://github.com/minetest-mods/ -> [Manifest link](http://minetest-mods.github.io/README.html) would be a better place to maintain this project.
Although I am not sure who to invite, thus one pending invitation for @thomasrudin.

**Comment by BuckarooBanzay** [comment]
> I believe the official https://github.com/minetest-mods/ -> Manifest link would be a better place to maintain this project.

The manifest is a bit conservative but i'm not going to rewrite that mod anyway, sounds good :+1: 

>  Although I am not sure who to invite, thus one pending invitation for @thomasrudin.

Please use this (new) one instead...
